-- Fasolka — stany magazynowe z Allegro, per rozmiar (uruchom w SQL Editor po seed.sql)
update produkty set stan = 64, stan_rozmiary = '{"128": 15, "134": 14, "140": 11, "146": 13, "152": 3, "158": 3, "164": 3, "170": 2}'::jsonb where id = 'bluzka-t-shirt-dziewczynki-bawelniana-koszul';
update produkty set stan = 37, stan_rozmiary = '{"104": 1, "110": 1, "116": 1, "122": 7, "128": 1, "134": 7, "140": 2, "146": 3, "152": 6, "158": 7, "164": 1, "170": 0}'::jsonb where id = 'spodnie-dresowe-chlopiece-wygodne-sportowe-k';
update produkty set stan = 37, stan_rozmiary = '{"98": 4, "104": 4, "110": 9, "116": 8, "122": 9, "128": 3}'::jsonb where id = 'spodnie-dresowe-chlopca-wygodne-do-przedszko';
update produkty set stan = 29, stan_rozmiary = '{"62": 0, "68": 0, "74": 0, "80": 0, "86": 0, "92": 0, "100": 29}'::jsonb where id = 'komplet-dresowy-niemowlaka-bluza-spodnie-baw';
update produkty set stan = 28, stan_rozmiary = '{"56": 7, "62": 7, "68": 7, "74": 7, "80": 0}'::jsonb where id = 'komplet-dresowy-niemowlaka-bluza-spodnie';
update produkty set stan = 35, stan_rozmiary = '{"146": 6, "152": 7, "158": 12, "164": 10}'::jsonb where id = 'spodnie-dresowe-chlopiece-chlopca-wygodne-sp';
update produkty set stan = 24, stan_rozmiary = '{"104": 1, "110": 3, "116": 3, "122": 3, "128": 2, "134": 2, "140": 2, "152": 2, "158": 4, "164": 2}'::jsonb where id = 'spodnie-dresowe-chlopiece-chlopca-wygodne-sp6';
update produkty set stan = 21, stan_rozmiary = '{"68": 0, "74": 0, "80": 0, "86": 0, "92": 0, "100": 21}'::jsonb where id = 'komplet-dresowy-niemowlaka-bluza-spodnie-baw7';
update produkty set stan = 35, stan_rozmiary = '{"62": 15, "68": 10, "74": 6, "80": 4}'::jsonb where id = 'polspiochy-niemowlece-ze-skarpetkami-elastyc';
update produkty set stan = 20, stan_rozmiary = '{"104": 1, "116": 3, "122": 4, "128": 0, "134": 3, "146": 2, "152": 0, "158": 2, "164": 5}'::jsonb where id = 'legginsy-prazkowane-dziewczece-z-wysokim-sta';
update produkty set stan = 18, stan_rozmiary = '{"62": 6, "68": 0, "74": 6, "80": 6, "86": 0}'::jsonb where id = 'komplet-chlopiecy-3-czesciowy-bluza-spodnie-';
update produkty set stan = 23, stan_rozmiary = '{"62": 10, "68": 5, "80": 8}'::jsonb where id = 'polspiochy-niemowlece-ze-skarpetkami-elastyc11';
update produkty set stan = 42, stan_rozmiary = '{"62": 18, "68": 0, "74": 15, "80": 8, "86": 1}'::jsonb where id = 'legginsy-niemowlece-spodnie-dzianinowe-prazk';
update produkty set stan = 21, stan_rozmiary = '{"98": 5, "104": 0, "110": 1, "116": 0, "122": 8, "134": 2, "140": 5, "146": 0}'::jsonb where id = 'prazkowane-legginsy-lekko-ocieplane-meszkiem';
update produkty set stan = 13, stan_rozmiary = '{"68": 4, "74": 3, "80": 5, "86": 1}'::jsonb where id = 'cz-komplet-dres-niemowlecy-bluza-bluzka';
update produkty set stan = 14, stan_rozmiary = '{"80": 3, "86": 0, "92": 8, "98": 2, "104": 1, "110": 0}'::jsonb where id = 'kamizelka-bezrekawnik-sweterkowa-dziewczynki';
update produkty set stan = 16, stan_rozmiary = null where id = 'czapka-noworodek-cm';
update produkty set stan = 15, stan_rozmiary = '{"56": 4, "62": 5, "68": 5, "74": 1}'::jsonb where id = 'cz-komplet-dres-niemowlecy-body-bluza';
update produkty set stan = 12, stan_rozmiary = '{"86": 1, "92": 1, "98": 1, "104": 1, "110": 1, "116": 4, "122": 1, "128": 2}'::jsonb where id = 'bluza-dziewczynki-z-nadrukiem-z-lekko';
update produkty set stan = 11, stan_rozmiary = '{"122": 3, "128": 0, "134": 2, "140": 3, "146": 0, "152": 2, "158": 1, "164": 0}'::jsonb where id = 'krotkie-spodenki-szorty-dresowe-dzieczynki-k';
update produkty set stan = 10, stan_rozmiary = '{"104": 2, "110": 2, "116": 0, "122": 2, "128": 0, "134": 2, "140": 0, "146": 2, "152": 0}'::jsonb where id = 'dres-2-cz-rozowy-komplet-dziewczynki-bluza';
update produkty set stan = 13, stan_rozmiary = '{"116": 4, "122": 2, "128": 6, "134": 1, "140": 0}'::jsonb where id = 'legginsy-welur-welurowe-dziewczynka-wysoki-s';
update produkty set stan = 10, stan_rozmiary = '{"122": 2, "128": 2, "134": 0, "140": 2, "146": 0, "152": 2, "158": 2, "164": 0}'::jsonb where id = 'koszulka-chlopieca-t-shert-krotki-rekaw';
update produkty set stan = 10, stan_rozmiary = '{"104": 1, "110": 1, "128": 2, "134": 2, "140": 2, "146": 2, "152": 0}'::jsonb where id = 'legginsy-getry-cienkie-dziewczynki-klasyczne';
update produkty set stan = 9, stan_rozmiary = '{"104": 2, "110": 2, "116": 2, "122": 2, "128": 1}'::jsonb where id = 'spodnie-dresowe-chlopiece-wygodne-sportowe-k24';
update produkty set stan = 9, stan_rozmiary = '{"68": 3, "74": 3, "80": 3}'::jsonb where id = 'komplet-chlopiecy-el-ogrodniczki-jeans-bluzk';
update produkty set stan = 11, stan_rozmiary = '{"98": 3, "104": 4, "110": 4}'::jsonb where id = 'dresik-dziecka-komplet-bluza-spodnie-wygodny';
update produkty set stan = 8, stan_rozmiary = '{"56": 2, "62": 2, "68": 2, "74": 2, "80": 0}'::jsonb where id = 'cz-komplet-chlopca-chrzest-wesele-i';
update produkty set stan = 10, stan_rozmiary = '{"80": 1, "92": 3, "98": 2, "104": 4, "110": 0}'::jsonb where id = 'kamizelka-bezrekawnik-sweterkowa-dzianina';
update produkty set stan = 25, stan_rozmiary = '{"98": 2, "104": 4, "110": 4, "116": 1, "122": 6, "128": 3, "134": 5}'::jsonb where id = 'spodnie-dresowe-chlopiece-chlopca-wygodne-sp29';
update produkty set stan = 8, stan_rozmiary = '{"80": 4, "86": 2, "92": 0, "98": 2}'::jsonb where id = 't-shirt-bluzka-dziewczeca-krotki-rekaw-do';
update produkty set stan = 25, stan_rozmiary = '{"80": 7, "86": 0, "92": 5, "98": 9, "104": 4, "110": 0}'::jsonb where id = 'kamizelka-bezrekawnik-sweterkowa-dzianina-au';
update produkty set stan = 23, stan_rozmiary = '{"110": 5, "116": 7, "122": 2, "128": 3, "134": 6, "140": 0}'::jsonb where id = 'gladkie-legginsy-ocieplane-meszkiem-dlugie-k';
update produkty set stan = 7, stan_rozmiary = '{"80": 2, "86": 0, "92": 2, "98": 2, "104": 1}'::jsonb where id = 'sweter-sweterek-chlopca-cieply-auto';
update produkty set stan = 8, stan_rozmiary = '{"62": 3, "68": 2, "74": 3, "80": 0}'::jsonb where id = 'legginsy-getry-polspiochy-dziewczynki-do-zlo';
update produkty set stan = 8, stan_rozmiary = '{"116": 2, "122": 2, "128": 3, "134": 1}'::jsonb where id = 'legginsy-prazkowane-dziewczece-cienkie';
update produkty set stan = 9, stan_rozmiary = '{"92": 4, "98": 0, "104": 3, "110": 2, "116": 0}'::jsonb where id = 'bluzka-dziecieca-w-serduszka-krotki-rekaw';
update produkty set stan = 7, stan_rozmiary = '{"86": 2, "92": 4, "98": 1, "104": 0}'::jsonb where id = 't-shirt-bluzka-dziewczeca-krotki-rekaw-do37';
update produkty set stan = 3, stan_rozmiary = '{"56": 1, "62": 1, "68": 1, "74": 0}'::jsonb where id = 'cz-komplet-dres-niemowlecy-bluza-body';
update produkty set stan = 6, stan_rozmiary = '{"110": 2, "116": 2, "122": 2}'::jsonb where id = 'kamizelka-chlopieca-pikowana-bezrekawnik-oci';
update produkty set stan = 6, stan_rozmiary = '{"116": 3, "122": 0, "146": 1, "164": 2}'::jsonb where id = 'spodnie-dresowe-dziewczynki-wygodne-do-szkol';
update produkty set stan = 6, stan_rozmiary = '{"110": 2, "116": 0, "122": 1, "128": 0, "146": 1, "152": 1, "158": 1, "164": 0}'::jsonb where id = 'legginsy-welur-welurowe-dziewczynki';
update produkty set stan = 6, stan_rozmiary = '{"110": 1, "122": 2, "128": 1, "134": 1, "146": 1, "152": 0}'::jsonb where id = 'spodnie-dresowe-chlopiece-chlopca-wygodne-sp42';
update produkty set stan = 6, stan_rozmiary = '{"80": 1, "98": 2, "104": 3, "110": 0}'::jsonb where id = 'getry-dziewczynki-legginsy-dzieciece';
update produkty set stan = 6, stan_rozmiary = '{"80": 1, "92": 2, "98": 0, "122": 1, "128": 2, "134": 0}'::jsonb where id = 'legginsy-getry-dziewczynki';
update produkty set stan = 11, stan_rozmiary = '{"92": 1, "98": 2, "104": 0, "110": 3, "116": 2, "122": 1, "128": 2}'::jsonb where id = 'legginsy-dzieciece-getry-rybaczki-szare';
update produkty set stan = 6, stan_rozmiary = '{"92": 2, "98": 0, "104": 1, "116": 3}'::jsonb where id = 'bluza-dziewczynki-z-nadrukiem-wykonana-z';
update produkty set stan = 8, stan_rozmiary = '{"98": 2, "104": 4, "110": 2, "116": 0}'::jsonb where id = 'legginsy-getry-cienkie-dziewczynki';
update produkty set stan = 10, stan_rozmiary = '{"98": 1, "104": 3, "110": 2, "116": 1, "122": 3}'::jsonb where id = 'legginsy-dzieciece-getry-rybaczki-prazkowane';
update produkty set stan = 6, stan_rozmiary = '{"116": 2, "122": 2, "128": 2, "134": 0}'::jsonb where id = 'kolarki-dzieciece-legginsy-prazkowane-sporto';
update produkty set stan = 5, stan_rozmiary = '{"98": 2, "104": 2, "110": 0, "116": 1, "122": 0}'::jsonb where id = 'spodenki-krotkie-szorty-dziewczynki-cm';
update produkty set stan = 6, stan_rozmiary = '{"92": 5, "98": 1, "104": 0}'::jsonb where id = 't-shirt-bluzka-dziewczeca-krotki-rekaw-do51';
update produkty set stan = 5, stan_rozmiary = '{"128": 2, "134": 1, "140": 1, "164": 1}'::jsonb where id = 'gladka-bluzka-chlopca-dziewczynki-z-krotkim';
update produkty set stan = 4, stan_rozmiary = '{"80": 1, "86": 0, "92": 1, "98": 1, "104": 1}'::jsonb where id = 'sweter-sweterek-chlopca-cieply-mis';
update produkty set stan = 4, stan_rozmiary = '{"56": 1, "62": 1, "68": 2}'::jsonb where id = 'pajacyk-chlopca-pajac-bawelna-zapinany-wypra';
update produkty set stan = 4, stan_rozmiary = '{"62": 1, "68": 1, "74": 1, "80": 1}'::jsonb where id = 'komplet-body-polspiochy-niemowlecy-babcia-tu';
update produkty set stan = 12, stan_rozmiary = '{"62": 3, "68": 3, "74": 3, "80": 3}'::jsonb where id = 'polspiochy-niemowlece-ze-skarpetkami-bawelna';
update produkty set stan = 4, stan_rozmiary = '{"62": 1, "68": 1, "74": 1, "80": 1}'::jsonb where id = 'body-dzieciece-body-niemowlece-dlugi-rekaw';
update produkty set stan = 8, stan_rozmiary = '{"62": 2, "68": 2, "74": 2, "80": 2}'::jsonb where id = 'body-dlugi-rekaw-babcia-tu-byla';
update produkty set stan = 4, stan_rozmiary = '{"80": 1, "86": 0, "98": 1, "104": 2, "110": 0}'::jsonb where id = 'kamizelka-bezrekawnik-sweterkowa';
update produkty set stan = 4, stan_rozmiary = '{"80": 1, "86": 0, "92": 1, "98": 2}'::jsonb where id = 'kamizelka-bezrekawnik-sweterkowa-akryl';
update produkty set stan = 8, stan_rozmiary = '{"92": 3, "98": 0, "104": 1, "110": 3, "116": 1}'::jsonb where id = 'spodnie-dresowe-chlopiece-chlopca-sportowe-l';
update produkty set stan = 8, stan_rozmiary = '{"86": 5, "92": 3, "98": 0}'::jsonb where id = 'spodnie-dresowe-chlopca-wygodne-do-zlobka';
update produkty set stan = 4, stan_rozmiary = '{"74": 1, "80": 2, "104": 1}'::jsonb where id = 'legginsy-spodnie-dzianinowe';
update produkty set stan = 4, stan_rozmiary = '{"68": 4, "74": 0}'::jsonb where id = 'legginsy-spodnie-dzianinowe-prazkowane';
update produkty set stan = 4, stan_rozmiary = '{"122": 1, "128": 1, "134": 0, "140": 1, "146": 0, "152": 1}'::jsonb where id = 'koszulka-chlopieca-t-shert-krotki-rekaw-bial';
update produkty set stan = 4, stan_rozmiary = '{"122": 1, "128": 1, "134": 0, "140": 1, "146": 0, "152": 1}'::jsonb where id = 'koszulka-chlopieca-t-shert-krotki-rekaw-czar';
update produkty set stan = 2, stan_rozmiary = '{"86": 2}'::jsonb where id = 'spodnie-dresowe-chlopca-wygodne-do-zlobka67';
update produkty set stan = 4, stan_rozmiary = null where id = 'czapka-noworodek-wczesniak-cm';
update produkty set stan = 4, stan_rozmiary = '{"116": 2, "122": 2}'::jsonb where id = 'bluza-kapturem-ciepla-gruba-rozpinana-chlopc';
update produkty set stan = 7, stan_rozmiary = null where id = 'welniane-skarpetki-buciki-niemowlece-bezucis';
update produkty set stan = 7, stan_rozmiary = null where id = 'welniane-skarpetki-buciki-niemowlece-bezucis71';
update produkty set stan = 4, stan_rozmiary = '{"80": 3, "86": 0, "92": 1}'::jsonb where id = 't-shirt-bluzka-dziewczeca-krotki-rekaw-do72';
update produkty set stan = 5, stan_rozmiary = '{"56": 2, "62": 3, "68": 0}'::jsonb where id = 'polspiochy-spodnie-bawelna-niemowlece';
update produkty set stan = 3, stan_rozmiary = '{"110": 1, "116": 1, "122": 1}'::jsonb where id = 'kamizelka-chlopieca-pikowana-bezrekawnik-oci74';
update produkty set stan = 3, stan_rozmiary = '{"56": 1, "62": 1, "68": 1}'::jsonb where id = 'pajac-dziwczynki-bawelna-zapinany-na-zatrzas';
update produkty set stan = 3, stan_rozmiary = '{"56": 1, "62": 1, "68": 1}'::jsonb where id = 'pajac-dziwczynki-bawelna-zapinany-na-zatrzas76';
update produkty set stan = 3, stan_rozmiary = '{"56": 1, "62": 1, "68": 1}'::jsonb where id = 'pajac-dziwczynki-bawelna-zapinany-na-zatrzas77';
update produkty set stan = 6, stan_rozmiary = '{"56": 6}'::jsonb where id = 'wyprawka-komplet-niemowlecy-rozmiar-bawelna';
update produkty set stan = 5, stan_rozmiary = '{"56": 5}'::jsonb where id = 'wyprawka-komplet-niemowlecy-elementowy-wielo';
update produkty set stan = 8, stan_rozmiary = '{"122": 8}'::jsonb where id = 'legginsy-prazkowane-dziewczece-z-wysokim-sta80';
update produkty set stan = 10, stan_rozmiary = '{"74": 4, "80": 0, "86": 4, "92": 0, "98": 2}'::jsonb where id = 'kamizelka-bezrekawnik-sweterkowa-dzianina-cz';
update produkty set stan = 3, stan_rozmiary = '{"116": 1, "122": 2}'::jsonb where id = 'spodnie-dresowe-chlopca-lekko-ocieplane-czar';
update produkty set stan = 4, stan_rozmiary = '{"62": 2, "68": 0, "74": 1, "80": 1, "86": 0}'::jsonb where id = 'legginsy-getry-spodnie-dzianinowe-prazkowane';
update produkty set stan = 5, stan_rozmiary = '{"56": 5, "62": 0}'::jsonb where id = 'komplet-wyprawka-noworodka-czesci-cm';
update produkty set stan = 4, stan_rozmiary = '{"86": 4}'::jsonb where id = 'spodnie-dresowe-chlopca-dzieciece-regulacja-';
update produkty set stan = 3, stan_rozmiary = '{"122": 1, "128": 0, "146": 1, "152": 0, "158": 1, "164": 0}'::jsonb where id = 'bluzka-z-dlugim-rekawem-dzieczynki-rozmiar';
update produkty set stan = 3, stan_rozmiary = '{"62": 1, "68": 1, "74": 0, "80": 1}'::jsonb where id = 'spodnie-polspiochy-niemowlece-cm-do-zlobka';
update produkty set stan = 4, stan_rozmiary = '{"40": 3, "41": 1}'::jsonb where id = 'par-skarpetki-skarpety-dzieciece';
update produkty set stan = 3, stan_rozmiary = '{"134": 2, "140": 1, "146": 0}'::jsonb where id = 'legginsy-prazkowane-dziewczynki-ocieplane-el';
update produkty set stan = 3, stan_rozmiary = '{"128": 2, "140": 1, "146": 0}'::jsonb where id = 'legginsy-prazkowane-dziewczynki-ocieplane-el90';
update produkty set stan = 3, stan_rozmiary = '{"110": 1, "116": 1, "134": 1}'::jsonb where id = 'bluza-chlopieca-z-kapturem-cienka-rozpinana';
update produkty set stan = 3, stan_rozmiary = '{"110": 1, "116": 0, "122": 2, "128": 0}'::jsonb where id = 'dzieciece-spodnie-dresowe-chlopiece-ocieplan';
update produkty set stan = 4, stan_rozmiary = null where id = 'welniane-skarpetki-buciki-niemowlece-bezucis93';
update produkty set stan = 3, stan_rozmiary = '{"104": 1, "110": 0, "116": 2}'::jsonb where id = 't-shirt-bluzka-dziewczeca-krotki-rekaw-do94';
update produkty set stan = 11, stan_rozmiary = '{"92": 1, "98": 4, "104": 6}'::jsonb where id = 'legginsy-getry-klasyczny-dlugie-cienkie';
update produkty set stan = 3, stan_rozmiary = '{"62": 1, "68": 1, "74": 1}'::jsonb where id = 'spodnie-polspiochy-niemowlece-zlobka';
update produkty set stan = 2, stan_rozmiary = '{"56": 1, "62": 1, "68": 0}'::jsonb where id = 'pajacyk-chlopca-pajac-bawelna-zapinany-wypra97';
update produkty set stan = 2, stan_rozmiary = '{"56": 2}'::jsonb where id = 'wyprawka-komplet-niemowlecy-rozmiar';
update produkty set stan = 4, stan_rozmiary = null where id = 'komplet-wyprawka-noworodka-czesci';
update produkty set stan = 2, stan_rozmiary = '{"104": 1, "116": 1}'::jsonb where id = 'spodnie-dresowe-chlopiece-chlopca-sportowe-b';
update produkty set stan = 2, stan_rozmiary = '{"134": 1, "140": 1}'::jsonb where id = 'spodnie-dresowe-lekko-ocieplane-chlopiece-wy';
update produkty set stan = 2, stan_rozmiary = '{"68": 1, "74": 1, "80": 0}'::jsonb where id = 'legginsy-akryl-spodnie-dzianinowe-prazkowane';
update produkty set stan = 4, stan_rozmiary = '{"122": 4, "128": 0}'::jsonb where id = 'spodenki-szorty-dresowe-chlopiece-koszykarsk';
update produkty set stan = 2, stan_rozmiary = '{"86": 2}'::jsonb where id = 'sukienka-dziewczynki-dlugi-rekaw-rozmiar';
update produkty set stan = 2, stan_rozmiary = '{"86": 2}'::jsonb where id = 'spodnie-dresowe-chlopca-dzieciece-regulacja-105';
update produkty set stan = 3, stan_rozmiary = '{"86": 3}'::jsonb where id = 'spodnie-dresowe-chlopca-dzieciece-regulacja-106';
update produkty set stan = 1, stan_rozmiary = '{"56": 1, "62": 0}'::jsonb where id = 'komplet-wyprawka-noworodka-czesci-cm107';
update produkty set stan = 2, stan_rozmiary = '{"74": 1, "80": 1, "86": 0}'::jsonb where id = 'pajac-pajacyk-prazkowany-kombinezon-rozmiar';
update produkty set stan = 2, stan_rozmiary = '{"104": 1, "110": 0, "116": 1}'::jsonb where id = 'spodnie-dresowe-dziewczynki-wygodne-do-przed';
update produkty set stan = 2, stan_rozmiary = '{"98": 1, "104": 1, "110": 0}'::jsonb where id = 'spodnie-dresowe-dziewczynki-wygodne-do-przed110';
update produkty set stan = 2, stan_rozmiary = '{"98": 2, "104": 0, "128": 0}'::jsonb where id = 'legginsy-dzieciece-getry-rybaczki-czarne';
update produkty set stan = 2, stan_rozmiary = null where id = 'czapka-noworodek-cm-welur';
update produkty set stan = 2, stan_rozmiary = '{"104": 2, "110": 0}'::jsonb where id = 'bluza-dziewczynki-z-kapturem-sportowa';
update produkty set stan = 4, stan_rozmiary = '{"74": 4}'::jsonb where id = 'spodnie-dresowe-chlopca-wygodne-do-zlobka114';
update produkty set stan = 2, stan_rozmiary = '{"128": 2}'::jsonb where id = 'bluza-z-kapturem-chlopieca-lekko-ocieplana';
update produkty set stan = 3, stan_rozmiary = '{"104": 2, "110": 0, "116": 1, "122": 0}'::jsonb where id = 'spodnie-dresowe-dziewczynki-wygodne-do-przed116';
update produkty set stan = 3, stan_rozmiary = '{"116": 3, "122": 0}'::jsonb where id = 'legginsy-prazkowane-spodnie-dzieciece-z-kies';
update produkty set stan = 2, stan_rozmiary = '{"110": 1, "116": 0, "122": 1, "128": 0}'::jsonb where id = 'bluza-welurowa-dziewczeca-z-kapturem-rozpina';
update produkty set stan = 2, stan_rozmiary = '{"74": 1, "80": 0, "86": 1, "92": 0}'::jsonb where id = 'kamizelka-bezrekawnik-sweterkowa-dzianina-cz119';
update produkty set stan = 3, stan_rozmiary = '{"98": 0, "100": 3}'::jsonb where id = 'bluzka-krotki-rekaw-koszulka-do-przedszkola';
update produkty set stan = 2, stan_rozmiary = '{"104": 2}'::jsonb where id = 'legginsy-dzieciece-prazkowanew-kwiatki-do-pr';
update produkty set stan = 2, stan_rozmiary = null where id = 'czapka-noworodek-wczesniak-cm122';
update produkty set stan = 6, stan_rozmiary = null where id = 'czapka-niemowleca-wiazana';
update produkty set stan = 2, stan_rozmiary = '{"56": 2}'::jsonb where id = 'polspiochy-dziewczynak-noworodek';
update produkty set stan = 2, stan_rozmiary = '{"62": 1, "68": 1}'::jsonb where id = 'legginsy-getry-dziewczynki-niemowelece-cm';
update produkty set stan = 2, stan_rozmiary = '{"68": 2, "74": 0}'::jsonb where id = 'spodnie-dresowe-ocieplane-polarem-cm-roz';
update produkty set stan = 2, stan_rozmiary = null where id = 'lekkie-buciki-niemowlece-niechodki-materialo';
update produkty set stan = 1, stan_rozmiary = '{"98": 1, "110": 0}'::jsonb where id = 'legginsy-dzieciece-legginsy-dziewczynki-fiol';
update produkty set stan = 2, stan_rozmiary = '{"98": 2, "104": 0}'::jsonb where id = 'legginsy-dzieciece-legginsy-dziewczynki-gran';
update produkty set stan = 1, stan_rozmiary = '{"68": 1}'::jsonb where id = 'pajacyk-chlopca-pajac-bawelna-zapinany-wypra130';
update produkty set stan = 1, stan_rozmiary = '{"92": 1}'::jsonb where id = 'kamizelka-bezrekawnik-sweterkowa-auto-granat';
update produkty set stan = 1, stan_rozmiary = '{"98": 1}'::jsonb where id = 'kamizelka-bezrekawnik-sweterkowa-mis';
update produkty set stan = 1, stan_rozmiary = '{"98": 1}'::jsonb where id = 'kamizelka-bezrekawnik-sweterkowa-dzianina-sz';
update produkty set stan = 1, stan_rozmiary = '{"122": 1}'::jsonb where id = 'spodnie-dresowe-chlopca-lekko-ocieplane-graf';
update produkty set stan = 1, stan_rozmiary = '{"122": 1}'::jsonb where id = 'spodnie-dresowe-chlopiece-chlopca-wygodne-sp135';
update produkty set stan = 1, stan_rozmiary = '{"140": 1}'::jsonb where id = 'spodnie-dresowe-chlopiece-wygodne-sportowe';
update produkty set stan = 1, stan_rozmiary = '{"68": 1}'::jsonb where id = 'cz-komplet-dres-niemowlecy-bluzka-bluza';
update produkty set stan = 1, stan_rozmiary = '{"86": 1}'::jsonb where id = 'spodnie-dresowe-chlopca-wygodne-do-zlobka138';
update produkty set stan = 1, stan_rozmiary = '{"122": 1, "128": 0}'::jsonb where id = 'krotkie-spodenki-dresowe-chlopiece-koszykars';
update produkty set stan = 1, stan_rozmiary = '{"122": 1, "128": 0}'::jsonb where id = 'krotkie-spodenki-dresowe-chlopiece-koszykars140';
update produkty set stan = 2, stan_rozmiary = '{"122": 2, "128": 0}'::jsonb where id = 'chlopiece-spodenki-sportowe-braz-kieszenie';
update produkty set stan = 2, stan_rozmiary = '{"122": 2, "128": 0}'::jsonb where id = 'chlopiece-spodenki-sportowe-czarne-kieszenie';
update produkty set stan = 1, stan_rozmiary = '{"104": 1, "110": 0}'::jsonb where id = 'sweter-sweterek-chlopca-akryl-cieply';
update produkty set stan = 1, stan_rozmiary = '{"134": 1, "140": 0}'::jsonb where id = 'bluza-bez-kaptura-cienka-rozpinana-chlopca';
update produkty set stan = 1, stan_rozmiary = '{"80": 1}'::jsonb where id = 'spodenki-krotkie-szorty-dzieczynki';
update produkty set stan = 1, stan_rozmiary = '{"134": 1}'::jsonb where id = 'spodnie-dresowe-chlopiece-chlopca-wygodne-sp146';
update produkty set stan = 2, stan_rozmiary = '{"86": 2}'::jsonb where id = 'spodnie-dresowe-chlopca-dzieciece-regulacja-147';
update produkty set stan = 1, stan_rozmiary = '{"86": 1}'::jsonb where id = 'spodnie-dresowe-chlopca-dzieciece-regulacja-148';
update produkty set stan = 1, stan_rozmiary = '{"56": 1, "62": 0}'::jsonb where id = 'pajac-niedrapki-czapka-komplet-noworodka-baw';
update produkty set stan = 1, stan_rozmiary = '{"62": 1, "68": 0}'::jsonb where id = 'pajac-pajacyk-niemowlecy-prazkowany-bawelnia';
update produkty set stan = 1, stan_rozmiary = '{"68": 1, "74": 0}'::jsonb where id = 'pajac-pajacyk-noworodek-prazkowany-bawelnian';
update produkty set stan = 1, stan_rozmiary = '{"62": 1, "68": 0, "100": 0}'::jsonb where id = 'pajac-pajacyk-bawelna-zapinany-na-zatrzaski';
update produkty set stan = 1, stan_rozmiary = '{"86": 1, "100": 0}'::jsonb where id = 'pajac-pajacyk-z-kapturem-bawelna-bez';
update produkty set stan = 1, stan_rozmiary = '{"56": 1, "62": 0}'::jsonb where id = 'pajac-noworodka-bawelna-zapinany-na-zatrzask';
update produkty set stan = 1, stan_rozmiary = '{"56": 1, "62": 0}'::jsonb where id = 'komplet-wyprawka-noworodka-czesci-cm155';
update produkty set stan = 1, stan_rozmiary = '{"110": 1, "116": 0}'::jsonb where id = 'bluzka-z-dlugim-rekawem-chlopca-rozmiar';
update produkty set stan = 1, stan_rozmiary = '{"80": 1, "86": 0}'::jsonb where id = 'sukienka-ala-tunika-dziewczynki-do-zlobka';
update produkty set stan = 1, stan_rozmiary = '{"62": 1}'::jsonb where id = 'body-dziewczynki-dlugi-rekaw-bawelna-rozmiar';
update produkty set stan = 1, stan_rozmiary = '{"68": 1}'::jsonb where id = 'body-dlugi-rekaw-dlka-dziewczynki-napisami';
update produkty set stan = 1, stan_rozmiary = '{"98": 1, "104": 0}'::jsonb where id = 'legginsy-getry-cienkie-dziewczynki-czarne';
update produkty set stan = 1, stan_rozmiary = '{"98": 1}'::jsonb where id = 'legginsy-prazkowane-dziewczece';
update produkty set stan = 1, stan_rozmiary = '{"80": 1, "86": 0}'::jsonb where id = 'sukienka-dziewczynki';
update produkty set stan = 2, stan_rozmiary = '{"104": 2, "110": 0}'::jsonb where id = 'spodenki-dzieczynki-krotkie-szorty-bawelna-c';
update produkty set stan = 4, stan_rozmiary = '{"98": 2, "104": 2}'::jsonb where id = 'spodenki-dziewczynki-krotkie-szorty-bawelna-';
update produkty set stan = 1, stan_rozmiary = '{"98": 1, "104": 0}'::jsonb where id = 'legginsy-dzieciece-getry-rybaczki-roz';
update produkty set stan = 4, stan_rozmiary = '{"110": 4}'::jsonb where id = 'legginsy-dzieciece-getry-rybaczki-szare-czar';
update produkty set stan = 1, stan_rozmiary = '{"74": 1}'::jsonb where id = 'komplet-niemowlecy-bluza-i-spodnie-cieply';
update produkty set stan = 5, stan_rozmiary = null where id = 'opaska-do-wlosow-z-grzebykiem-baza';
update produkty set stan = 1, stan_rozmiary = '{"68": 1, "74": 0}'::jsonb where id = 'komplet-niemowlecy-dziewczynki-ocieplany-pol';
update produkty set stan = 1, stan_rozmiary = '{"62": 1, "68": 0}'::jsonb where id = 'komplet-dziewczynki-bluzka-spodnie';
update produkty set stan = 1, stan_rozmiary = '{"68": 1, "74": 0}'::jsonb where id = 'komplet-dziewczynki-bluza-spodnie';
update produkty set stan = 2, stan_rozmiary = '{"68": 2, "74": 0}'::jsonb where id = 'komplet-chlopca-bluza-spodnie-do-zlobka';
update produkty set stan = 1, stan_rozmiary = '{"98": 1, "104": 0}'::jsonb where id = 'dzieciece-spodnie-dresowe-chlopiece-ocieplan173';
update produkty set stan = 3, stan_rozmiary = '{"86": 3, "92": 0}'::jsonb where id = 'legginsy-getry-dziewczynki-bawelna-lekko-oci';
update produkty set stan = 1, stan_rozmiary = null where id = 'czapka-noworodek-wiazana-zinowa';
update produkty set stan = 1, stan_rozmiary = null where id = 'welniane-skarpetki-buciki-niemowlece-bezucis176';
update produkty set stan = 5, stan_rozmiary = null where id = 'welniane-skarpetki-buciki-niemowlece-bezucis177';
update produkty set stan = 2, stan_rozmiary = null where id = 'welniane-skarpetki-buciki-niemowlece-bezucis178';
update produkty set stan = 2, stan_rozmiary = null where id = 'par-skarpetki-skarpety-dzieciece-bawelna-kol';
update produkty set stan = 2, stan_rozmiary = '{"41": 2}'::jsonb where id = 'par-skarpetki-skarpety-dzieciece-bawelna';
update produkty set stan = 4, stan_rozmiary = '{"122": 4}'::jsonb where id = 'dzwony-dziewczece-legginsy-ocieplane-prazkow';
update produkty set stan = 1, stan_rozmiary = '{"140": 1, "146": 0}'::jsonb where id = 'legginsy-prazkowane-dziewczynki-ocieplane-el182';
update produkty set stan = 1, stan_rozmiary = '{"140": 1, "146": 0}'::jsonb where id = 'legginsy-prazkowane-dziewczynki-ocieplane-el183';
update produkty set stan = 1, stan_rozmiary = '{"170": 1}'::jsonb where id = 'spodnie-dresowe-dziewczynki-wygodne';
update produkty set stan = 1, stan_rozmiary = '{"116": 1, "122": 0}'::jsonb where id = 'spodenki-krotkie-dresowe-chlopiece-kieszenie';
update produkty set stan = 1, stan_rozmiary = '{"110": 1}'::jsonb where id = 'spodenki-krotkie-dresowe-chlopiece-kieszenie186';
update produkty set stan = 2, stan_rozmiary = '{"92": 2}'::jsonb where id = 'legginsy-getry-dziewczynki-bawelna-lekko-oci187';
update produkty set stan = 2, stan_rozmiary = '{"80": 2}'::jsonb where id = 'legginsy-getry-dziewczynki-bawelna-lekko-oci188';
update produkty set stan = 1, stan_rozmiary = '{"116": 1}'::jsonb where id = 'spodnie-dresowe-chlopca-lekko-ocieplane-gran';
update produkty set stan = 1, stan_rozmiary = '{"140": 1}'::jsonb where id = 'bluza-chlopieca-z-kapturem-cienka-rozpinana190';
update produkty set stan = 1, stan_rozmiary = '{"116": 1, "122": 0}'::jsonb where id = 'bluza-z-kapturem-cienka-rozpinana-chlopca';
update produkty set stan = 1, stan_rozmiary = '{"134": 1, "140": 0}'::jsonb where id = 'bluza-z-kapturem-cienka-rozpinana-chlopca192';
update produkty set stan = 1, stan_rozmiary = '{"104": 1}'::jsonb where id = 'legginsy-dziewczynki-klasyczne-szare';
update produkty set stan = 1, stan_rozmiary = '{"104": 1, "110": 0}'::jsonb where id = 'sweter-sweterek-chlopca-cieply';
update produkty set stan = 1, stan_rozmiary = '{"98": 1}'::jsonb where id = 't-shirt-bluzka-dziewczeca-krotki-rekaw-do195';
update produkty set stan = 1, stan_rozmiary = '{"104": 1}'::jsonb where id = 'legginsy-getry-dziewczynki-ocieplane-zima-fu';
update produkty set stan = 2, stan_rozmiary = '{"110": 2, "116": 0}'::jsonb where id = 'legginsy-getry-dziewczynki-ocieplane-futerki';
update produkty set stan = 1, stan_rozmiary = '{"104": 1}'::jsonb where id = 'legginsy-getry-dziewczynki-ocieplane-zima-fu198';
update produkty set stan = 3, stan_rozmiary = '{"110": 3, "116": 0}'::jsonb where id = 'bluzka-dziecieca-w-serduszka-krotki-rekaw199';
update produkty set stan = 1, stan_rozmiary = '{"164": 1, "170": 0}'::jsonb where id = 'bluzka-oversize-krotki-rekaw-koszulka-do';
update produkty set stan = 2, stan_rozmiary = '{"80": 2}'::jsonb where id = 'komplet-dziewczynki-bluza-spodnie-do-zlobka';
update produkty set stan = 1, stan_rozmiary = null where id = 'welniane-skarpetki-buciki-niemowlece-bezucis202';
update produkty set stan = 2, stan_rozmiary = null where id = 'czapka-dzianiny-pomponem-przejsciowa';
update produkty set stan = 1, stan_rozmiary = '{"122": 1}'::jsonb where id = 'legginsy-getry-cienkie-dziewczynki-szary';
update produkty set stan = 1, stan_rozmiary = '{"104": 1}'::jsonb where id = 'legginsy-getry-cienkie-dziewczynki-szare';
update produkty set stan = 1, stan_rozmiary = '{"92": 1, "98": 0}'::jsonb where id = 'bluzka-dziewczeca-krotki-rekaw-bawelna-wygod';
update produkty set stan = 1, stan_rozmiary = '{"98": 1}'::jsonb where id = 'legginsy-dzieciece-legginsy-dziewczynki-kote';
update produkty set stan = 1, stan_rozmiary = '{"110": 1}'::jsonb where id = 'legginsy-dzieciece-legginsy-dziewczynki-kote208';
update produkty set stan = 1, stan_rozmiary = '{"104": 1}'::jsonb where id = 'legginsy-dzieciece-legginsy-dziewczynki-kote209';
update produkty set stan = 1, stan_rozmiary = '{"92": 1}'::jsonb where id = 'legginsy-getry-cienkie-dziewczynki-czerwone';
update produkty set stan = 1, stan_rozmiary = '{"164": 1}'::jsonb where id = 'bluza-bez-kaptura-ciepla-rozpinana-bluza';
update produkty set stan = 1, stan_rozmiary = '{"104": 1}'::jsonb where id = 'getry-dziewczynki-legginsy-klasyczne';
update produkty set stan = 1, stan_rozmiary = '{"122": 1}'::jsonb where id = 'legginsy-getry-cienkie-dziewczynki-klasyczne213';
update produkty set stan = 2, stan_rozmiary = '{"104": 2}'::jsonb where id = 'legginsy-dzieciece-dziewczynki-kotek-czarny';
update produkty set stan = 3, stan_rozmiary = '{"98": 3}'::jsonb where id = 'legginsy-dzieciece-dziewczynki-kotek-czarne';
update produkty set stan = 1, stan_rozmiary = '{"74": 1, "80": 0}'::jsonb where id = 'spodnie-polspiochy-niemowlece';
update produkty set stan = 1, stan_rozmiary = '{"62": 1}'::jsonb where id = 'polspiochy-spodnie-bawelna-niemowlece-gladki';
update produkty set stan = 1, stan_rozmiary = '{"68": 1}'::jsonb where id = 'legginsy-getry-dziewczynki-niemowelece';
update produkty set stan = 1, stan_rozmiary = '{"74": 1}'::jsonb where id = 'legginsy-polspiochy-niemowelece-cm';
update produkty set stan = 1, stan_rozmiary = '{"68": 1}'::jsonb where id = 'legginsy-getry-dziewczynki-niemowelece-czerw';
update produkty set stan = 1, stan_rozmiary = '{"74": 1}'::jsonb where id = 'spodnie-niemowlece-wygodne-cm';
update produkty set stan = 1, stan_rozmiary = '{"80": 1}'::jsonb where id = 'spodnie-dresowe-prazkowane-cm-niemowlece-mie';
update produkty set stan = 1, stan_rozmiary = '{"74": 1}'::jsonb where id = 'spodnie-niemowlece-baggy-wygodne-cm';
update produkty set stan = 1, stan_rozmiary = '{"62": 1, "68": 0}'::jsonb where id = 'polspiochy-spodnie-bawelna-niemowlece-niebie';
update produkty set stan = 1, stan_rozmiary = '{"74": 1}'::jsonb where id = 'body-dlugi-rekaw-male-jest-piekne';
update produkty set stan = 1, stan_rozmiary = '{"62": 1, "68": 0}'::jsonb where id = 'komplet-chlopca-bluza-spodnie';
update produkty set stan = 3, stan_rozmiary = '{"98": 3}'::jsonb where id = 'kamizelka-bezrekawnik-sweterkowa-akryl-mis';
update produkty set stan = 2, stan_rozmiary = '{"104": 2, "110": 0}'::jsonb where id = 'sweter-sweterek-chlopca-cieply-grafitowy';
update produkty set stan = 2, stan_rozmiary = null where id = 'welniane-skarpetki-buciki-niemowlece-bezucis229';
update produkty set stan = 1, stan_rozmiary = null where id = 'welniane-skarpetki-buciki-niemowlece-bezucis230';
update produkty set stan = 1, stan_rozmiary = null where id = 'welniane-skarpetki-buciki-niemowlece-bezucis231';
update produkty set stan = 1, stan_rozmiary = null where id = 'welniane-skarpetki-buciki-niemowlece-bezucis232';
update produkty set stan = 2, stan_rozmiary = null where id = 'welniane-skarpetki-buciki-niemowlece-bezucis233';
update produkty set stan = 2, stan_rozmiary = null where id = 'welniane-skarpetki-buciki-niemowlece-dziewcz';
update produkty set stan = 2, stan_rozmiary = null where id = 'welniane-skarpetki-buciki-niemowlece-dziewcz235';
update produkty set stan = 2, stan_rozmiary = '{"104": 2}'::jsonb where id = 'legginsy-dzieciece-legginsy-dziewczynki-serc';
update produkty set stan = 3, stan_rozmiary = '{"92": 3}'::jsonb where id = 'legginsy-dzieciece-legginsy-dziewczynki-gran237';
